version: "3.9"
services:
  golang:
    container_name: elastic-golang
    image: coderbillzay/elastic-golang
    ports:
      - '2160:2160'
    env_file:
      - .env
    volumes:
      - ./:/server
    restart: always